App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('cart/', views.cart_view, name="cart"),
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('product/<pk>/comment/', views.create_comment, name='comment'),
    path('product/<pk1>/update_comment/<pk2>',
         views.edit_comment, name='update_comment'),
    path('author/<pk>', views.AuthorDetail.as_view(), name='author'),
    path('category/<pk>', views.CategoryDetail.as_view(), name='category'),
    path('publisher/<pk>', views.PublisherDetail.as_view(), name='publisher'),
    path('writers/', views.WritersList.as_view(), name='writers'),
]

Online_Book_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


class Author(models.Model):
    name = models.CharField(max_length=264, blank=True)
    description = models.TextField(
        max_length=1000, verbose_name='Description', blank=True)
    isMVP = models.BooleanField(default=False)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return str(self.name)


class Publisher(models.Model):
    name = models.CharField(max_length=264, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    mainimage = models.ImageField(upload_to='products')
    name = models.CharField(max_length=264)
    isPublished = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category')
    publisher = models.ForeignKey(
        Publisher, on_delete=models.CASCADE, related_name='publisher')
    authors = models.ManyToManyField(Author, related_name='authors')
    description = models.TextField(max_length=2000, verbose_name='Description')
    page_no = models.IntegerField(default=1)
    date_published = models.IntegerField(default=0)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]


class Comment(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='product_comment')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('comment_date',)

    def __str__(self):
        return self.comment


class Likes(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='liked_product')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return self.user + " likes " + self.blog

    class Meta:
        verbose_name_plural = "Likes"

App_Shop/forms.py
from django import forms
from App_Shop.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Shop/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy

# Import views
from django.views.generic import ListView, DetailView, UpdateView

# Models
from App_Shop.models import Product, Author, Category, Publisher, Comment, Likes
from App_Login.models import Profile

# Forms
from App_Shop.forms import CommentForm

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin

# Decorator
from django.contrib.auth.decorators import login_required

# Create your views here.


class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'

    def get_queryset(self):
        query = self.request.GET.get('search', '')
        if query:
            object_list = self.model.objects.filter(name__icontains=query)
        else:
            object_list = self.model.objects.all()
        return object_list


class ProductDetail(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'App_Shop/product_detail.html'


@login_required
def create_comment(request, pk):
    product = Product.objects.get(pk=pk)
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            print(request.user)
            comment.user = request.user
            comment.product = product
            comment.save()
            return redirect('App_Shop:product_detail', pk=pk)

    dict = {
        'product': product,
        'comment_form': comment_form
    }
    return render(request, 'App_Shop/comment_form.html', context=dict)


@login_required
def edit_comment(request, pk1, pk2):
    product = get_object_or_404(Product, pk=pk1)
    comment = get_object_or_404(Comment, pk=pk2)
    print(comment)
    form = CommentForm(instance=comment)
    if request.method == "POST":
        form = CommentForm(data=request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            form = CommentForm(instance=comment)
            return HttpResponseRedirect(reverse_lazy('App_Shop:product_detail', kwargs={'pk': pk1}))
    return render(request, 'App_Shop/edit_comment.html', context={'form': form, 'product': product})


class WritersList(ListView):
    model = Author
    template_name = 'App_Shop/writers.html'


class AuthorDetail(DetailView):
    model = Author
    template_name = 'App_Shop/Author.html'


class CategoryDetail(DetailView):
    model = Category
    template_name = 'App_Shop/Category.html'


class PublisherDetail(DetailView):
    model = Publisher
    template_name = 'App_Shop/Publisher.html'

templates/App_Shop/Author.html
{% extends 'base.html' %}

{%block title_block %} Author {%endblock%}

{% block body_block %}

<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{object.profile_pic}}" width="250px" height="250px" class="rounded-circle">
    </div>
    <div class="col-sm-8">
        <h3>{{object.name}}</h3>
        <br>
        <h6>{{object.description | linebreaks}}</h6>
    </div>
</div>

<br>
<br>
<h4>Writer's Books: {{object.authors.count}}</h4>
<br>
<div class="row">

    {% for book in object.authors.all %}
    <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="/media/{{book.mainimage}}" style="width:200px; height: 300px;">
            </div>
            <figcaption class=" info-wrap">
                <h5 class="title"><a href="{% url 'App_Shop:product_detail' pk=book.pk %}">{{book.name}}</a>
                </h5>

                <span>written by, </span>
                {% for author in book.authors.all %}
                <h6 class="title" style="font-size: 15px;"><a
                        href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}} </a>
                </h6>
                {% endfor %}
                </h6>
                <div class="action-wrap">
                    <div class="price-wrap h5">
                        <span class="price-new">&#2547; {{book.price|floatformat:2}}</span>
                        <span class="price-old"><strike>&#2547; {{book.old_price|floatformat:2}}</strike></span>
                    </div>
                </div>
            </figcaption>
        </figure>
    </div>
    {% endfor %}
</div>

{% endblock body_block %}

templates/App_Shop/Category.html
{% extends 'base.html' %}

{%block title_block %} Category {%endblock%}

{% block body_block %}

<h4>{{object.title}} books list</h4>
<br>
<div class="row">

    {% for book in object.category.all %}
    <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="/media/{{book.mainimage}}" style="width:200px; height: 300px;">
            </div>
            <figcaption class=" info-wrap">
                <h5 class="title"><a href="{% url 'App_Shop:product_detail' pk=book.pk %}">{{book.name}}</a>
                </h5>

                <span>written by, </span>
                {% for author in book.authors.all %}
                <h6 class="title" style="font-size: 15px;"><a
                        href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}} </a>
                </h6>
                {% endfor %}
                </h6>
                <div class="action-wrap">
                    <div class="price-wrap h5">
                        <span class="price-new">&#2547; {{book.price|floatformat:2}}</span>
                        <span class="price-old"><strike>&#2547; {{book.old_price|floatformat:2}}</strike></span>
                    </div>
                </div>
            </figcaption>
        </figure>
    </div>
    {% endfor %}
</div>

{% endblock body_block %}

templates/App_Shop/Publisher.html
{% extends 'base.html' %}

{%block title_block %} Publisher {%endblock%}

{% block body_block %}

<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{object.profile_pic}}" width="250px" height="250px" class="rounded-circle">
    </div>
    <div class="col-sm-8">
        <h3>{{object.name}}</h3>
    </div>
</div>

<br>
<br>
<h4>Publisher's Books: {{object.authors.count}}</h4>
<br>
<div class="row">

    {% for book in object.publisher.all %}
    <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="/media/{{book.mainimage}}" style="width:200px; height: 300px;">
            </div>
            <figcaption class=" info-wrap">
                <h5 class="title"><a href="{% url 'App_Shop:product_detail' pk=book.pk %}">{{book.name}}</a>
                </h5>

                <span>written by, </span>
                {% for author in book.authors.all %}
                <h6 class="title" style="font-size: 15px;"><a
                        href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}} </a>
                </h6>
                {% endfor %}
                </h6>
                <div class="action-wrap">
                    <div class="price-wrap h5">
                        <span class="price-new">&#2547; {{book.price|floatformat:2}}</span>
                        <span class="price-old"><strike>&#2547; {{book.old_price|floatformat:2}}</strike></span>
                    </div>
                </div>
            </figcaption>
        </figure>
    </div>
    {% endfor %}
</div>

{% endblock body_block %}

templates/App_Shop/comment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}

<h2>Write your comment for "{{product.name}}"</h2>
<form method="POST">
    {% csrf_token %}
    {{comment_form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">Comment</button>
</form>
{% endblock body_block %}

templates/App_Shop/edit_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<h2>Update your comment for "{{product.name}}"</h2>
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">Update</button>
</form>

{% endblock %}

templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}


<div class="container my-5">

    <h2 class="my-5">Featured Books</h2>
    <div class="row">
        {% for product in object_list %}
        {% if product.isPublished %}
        <div class="col-md-6 col-sm-12 col-lg-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.mainimage}}" style="width:200px; height: 300px;">
                </div>
                <figcaption class=" info-wrap">
                    <h5 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a>
                    </h5>

                    <span>written by, </span>
                    {% for author in product.authors.all %}
                    <h6 class="title" style="font-size: 15px;"><a
                            href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}} </a>
                    </h6>
                    {% endfor %}
                    </h6>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                            <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
                        </div>
                    </div>
                </figcaption>
            </figure>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock body_block %}

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href=""><img src="/media/{{product.mainimage}}" style="width: 450px; height: 500px;"></a>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div>
                        <h3>Number of Pages: {{product.page_no}}</h3>
                        <h3>First Published: {{product.date_published}}</h3>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{product.name}}</h3>

                    {% for author in product.authors.all %}
                    <a href="{% url 'App_Shop:author' pk=author.pk %}">
                        <h6>{{author.name}}</h6>
                    </a>
                    {% endfor %}

                    <span>Published by <a href="{% url 'App_Shop:publisher' pk=product.publisher.pk %}">
                            <span>{{product.publisher.name}}</span>
                        </a></span>

                    <br>

                    <span>Category : <a href="{% url 'App_Shop:category' pk=product.category.pk %}">
                            <span>{{product.category.title}}</span>
                        </a></span>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">BDT &#2547;<span class="num">{{product.price}}</span></span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>
                            <p>{{product.description|linebreaks}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'App_Order:add' pk=product.pk %}"
                        class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i> Add
                        to Cart</a>
                </article>
            </aside>
        </div>
        <br>
        <br>
        <div class="row">
            <div class="col-11">
                <hr>
                <h5>Comments </h5>


                {% if product.product_comment.count >= 1 %}
                {% for comment in product.product_comment.all %}

                {% if comment.user.profile.profile_pic %}
                <img src="/media/{{comment.user.profile.profile_pic}}" width="40px" height="40px"
                    class="rounded-circle">
                {% else %}
                <img src="/media/avatar-male.jpg" width="40px" height="40px" class="rounded-circle">
                {% endif %}
                <span>
                    {% if comment.user.profile.full_name == '' %}
                    <b>{{comment.user}}</b>
                    {% else %}
                    <b>{{comment.user.profile.full_name}}</b>
                    {% endif %}
                    - {{comment.comment}}<br>
                    <h6>Base: {{comment.comment_date}}</h6>
                    <h6>updated: {{comment.comment_update}}</h6>
                </span>

                {% if comment.user == user %}
                <a href="{% url 'App_Shop:update_comment' pk1=product.pk pk2=comment.pk %}"
                    class="btn btn-warning btn-sm">Edit</a>
                {% endif %}

                <hr>
                {% endfor %}
                {% else %}
                <div class="container">
                    <h6>No one commented yet. Be first to comment!</h6>
                </div>
                <br>
                <br>
                {% endif %}


            </div>
            <div class="col-1">
                <a href="{% url 'App_Shop:comment' pk=product.pk %}" class="btn btn-primary btn-sm">Comment</a>
            </div>
        </div>
    </div>
</div>

{% endblock body_block %}

templates/App_Shop/writers.html
{% extends 'base.html' %}

{%block title_block %} Author {%endblock%}

{% block body_block %}

<div class="container">
    <h2 class="my-5">Writer of the month</h2>

    {% for author in object_list %}
    {% if author.isMVP %}
    <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="/media/{{author.profile_pic}}" style="width:200px; height: 300px;">
            </div>
            <figcaption class=" info-wrap">
                <h5 class="title"><a href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}}</a>
                </h5>
                <span>Total Books: {{author.authors.count}} </span>
            </figcaption>
        </figure>
    </div>
    {% endif %}
    {% endfor %}
</div>

<h2 class="my-5">Featured Writers</h2>
<div class="row">

    {% for author in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="/media/{{author.profile_pic}}" style="width:200px; height: 300px;">
            </div>
            <figcaption class=" info-wrap">
                <h5 class="title"><a href="{% url 'App_Shop:author' pk=author.pk %}">{{author.name}}</a>
                </h5>
                <span>Total Books: {{author.authors.count}} </span>
            </figcaption>
        </figure>
    </div>
    {% endfor %}


</div>

{% endblock %}