App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('cart/', views.cart_view, name="cart"),
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('product/<pk>/comment/', views.create_comment, name='comment'),
    path('product/<pk1>/update_comment/<pk2>',
         views.edit_comment, name='update_comment'),
    path('author/<pk>', views.AuthorDetail.as_view(), name='author'),
    path('category/<pk>', views.CategoryDetail.as_view(), name='category'),
    path('publisher/<pk>', views.PublisherDetail.as_view(), name='publisher'),
    path('writers/', views.WritersList.as_view(), name='writers'),
]

Online_Book_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title_block %} Online Book Shop {% endblock %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container" style="padding-top: 40px;">
        <div class="messages container mt-2">
            {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% block body_block %}

        {% endblock body_block %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Online Book Shop</a>
        <ul class="navbar-nav mr-auto">
            &nbsp; &nbsp; &nbsp; &nbsp;
            <form class="form-inline" method="GET">
                <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search Book">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <li class="nav-item">
                <a href="{% url 'App_Shop:writers' %}">Writers</a>
            </li>
        </ul>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'App_Order:cart' %}" class="nav-link">
                        <i class="fa fa-shopping-cart"></i> Cart
                        <span class="badge badge-light">{{request.user | cart_total}}</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i>
                        {{request.user.profile.username}}</a>
                    <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                        <a class="dropdown-item" href="#">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>